### ISSUE TITLE
BUG反馈 : 关机后镜头耗电

### ISSUE THREAD

**Issue by wd-veloce** [dayotong/Viltrox85.8eMountBugReport#2]
## 问题类型 / Type

BUG反馈

## 问题描述 / Description

机器电量在100%时候关闭，期间一直使用唯卓85镜头挂机且并未开机，大致在两天之后电量耗尽无法开机。

机身 / Camera：Sony alpha 7
镜头 / Lens：Viltrox 85.8 E Mount
固件版本号 / Firmware Version：v1.0.10

## 问题提出者 / Reporter

唯卓仕VILTROX产品交流群 - 如鸿 - QQ：2468155138

**Comment by dayotong** [comment]
手上暂时没有A7,过两天来了之后测试一下,镜头目前版本v1.0.12的待机电流是30uA,原厂FE85是20uA的水平,用户应该不会感觉到有区别,请升级镜头固件再测试一下

**Comment by dayotong** [comment]
昨天早上测试一台alpha6400待机功耗,到现在24小时开机电量100%(v1.0.12),等alpha7来了再测试

**Comment by wd-veloce** [comment]
昨日已通知问题提出者，并建议其更新固件

**Comment by dayotong** [comment]
bug修复,新固件:
[https://github.com/dayotong/Viltrox85.8eMountBugReport/releases/tag/v1.0.13](url)

**Comment by wd-veloce** [comment]
已收到，正在准备整理并转发到群内

**Comment by dayotong** [comment]
bug修复,新固件:
[新固件地址](https://github.com/dayotong/Viltrox85.8eMountBugReport/releases/tag/v1.0.13)
