### ISSUE TITLE
BUG反馈：实时预览出现条纹

### ISSUE THREAD

**Issue by wd-veloce** [dayotong/Viltrox85.8eMountBugReport#3]
## 问题类型 / Type

BUG反馈

## 问题描述 / Description

机器在对着白色墙壁，使用手动方式对焦墙壁后，机器的屏幕上和evf中出现横向的条纹。但是在拍摄之后得到的照片中条纹消失。

![` )%W _L)631R(F1K9M12$M](https://user-images.githubusercontent.com/41357935/65382174-a1406a00-dd31-11e9-8a2c-3a4340321207.png)

![61 439$(T~8%P`6HF%W511](https://user-images.githubusercontent.com/41357935/65382199-2b88ce00-dd32-11e9-8382-adc47af418fe.jpg)

可以看出红框圈出的地方和两框之内的地方颜色不一，以及evf中有明显横向深浅不一的条纹。手机拍摄的照片较不明显。实际肉眼能看到明显的条纹。

机身 / Camera：Sony alpha 7
镜头 / Lens：Viltrox 85.8 E Mount
固件版本号 / Firmware Version：v1.0.12

## 问题提出者 / Reporter

唯卓仕VILTROX产品交流群 - 彼时明月 - QQ：651911845

**Comment by wd-veloce** [comment]
Reporter增加反馈：他手里的镜头中只有唯卓85/1.8E出现这个问题，其他的镜头在实时预览时候都非常正常。

**Comment by dayotong** [comment]
在A7R3上有重现轻微的条纹,应该和室内光源50Hz频闪有关,机身设置成NTSC之后现象消失,具体问题还要调查.

**Comment by dayotong** [comment]
屏幕条纹跟光源频闪和CMOS滚动快门有关,应该属于正常现象,问题关闭.
室内有频闪光源的地方尽量使用机械快门.
