### ISSUE TITLE
BUG反馈：DMF和MF中手动转动对焦环失灵

### ISSUE THREAD

**Issue by wd-veloce** [dayotong/Viltrox85.8eMountBugReport#5]
## 问题类型 / Type

BUG反馈

## 问题描述 / Description

AFC和AFS模式下正常，DMF和MF手动转动对焦环对焦无反应，关机拧下镜头之后（完全断电）再重新装上时候DMF和MF状态下手动对焦环恢复正常工作，在机身开关短暂关闭后再打开时候再次失效

机身 / Camera：Sony alpha 7
镜头 / Lens：Viltrox 85.8 E Mount
固件版本号 / Firmware Version：v1.0.13

## 问题提出者 / Reporter

唯卓仕VILTROX产品交流群 - 彼时明月 - QQ：651911845

**Comment by wd-veloce** [comment]
已经有两个人反馈这个问题

**Comment by wd-veloce** [comment]
我个人盲猜是DMF和MF状态下没有从休眠中（1.0.13版所设置的状态）重新启动

**Comment by dayotong** [comment]
收到,正在调查

**Comment by dayotong** [comment]
问题已修复,[新固件](https://github.com/dayotong/Viltrox85.8eMountBugReport/releases/tag/v1.0.14)

**Comment by wd-veloce** [comment]
已收到，正在整理准备转载到群内
