### ISSUE TITLE
BUG反馈：AFC无故失效

### ISSUE THREAD

**Issue by wd-veloce** [dayotong/Viltrox85.8eMountBugReport#9]
## 问题类型 / Type

BUG反馈

## 问题描述 / Description

在使用AFC模式的情况下，无故出现无法对焦的情况，在切换AFS之后变得正常。拍摄环境没有在暗光等环境下。

机身 / Camera：Sony alpha 7
镜头 / Lens：Viltrox 85.8 E Mount
固件版本号 / Firmware Version：v1.0.14

## 问题提出者 / Reporter

唯卓仕VILTROX产品交流群 - 如鸿 - QQ：2468155138

**Comment by dayotong** [comment]
无法对焦是指半按快门没有任何反应是吗?

**Comment by wd-veloce** [comment]
> 无法对焦是指半按快门没有任何反应是吗?

按照反馈者来说是这样的

**Comment by dayotong** [comment]
> > 无法对焦是指半按快门没有任何反应是吗?
> 
> 按照反馈者来说是这样的

暂时没有检查到这个问题,有可能是个别镜头或机身的电子触电配合出问题,问题关闭
